services:
  db:
    image: postgres:16-alpine
    container_name: beautique-db
    environment:
      POSTGRES_USER: beautique
      POSTGRES_PASSWORD: beautique
      POSTGRES_DB: beautique
    volumes:
      - db-beautique:/var/lib/postgresql/data
      - ./init-beautique-schema.sql:/docker-entrypoint-initdb.d/init-beautique-schema.sql
    ports:
      - "5432:5432"
    networks:
      - beautique_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U beautique -d beautique"]
      interval: 10s
      timeout: 5s
      retries: 5
  rabbitmq:
    image: rabbitmq:3-management
    container_name: beautique-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: beautique
      RABBITMQ_DEFAULT_PASS: beautique
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - beautique_network
    mongodb:
      image: mongo:latest
      hostname: beautique-mongodb
      environment:
        MONGO_INITDB_ROOT_USERNAME: beautique
        MONGO_INITDB_ROOT_PASSWORD: beautique
      volumes:
        - db-mongo:/data/db
        - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
      ports:
        - "27017:27017"
      networks:
        - beautique_network


networks:
  beautique_network:
    driver: bridge

volumes:
  db-beautique: